language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - sudo docker --version # print the version for logging
  - sudo docker build -t udagram-api-feed ./udagram-api-feed
  - sudo docker tag udagram-frontend ibrahimsedhom/udagram-api-feed:v1

after_success:
  - sudo docker login --username "ibrahimsedhom"  --password "1234_2023"
  - sudo docker push ibrahimsedhom/udagram-api-feed:v1
