language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-frontend ibrahimsedhom/udagram-api-feed:latest

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-frontend ibrahimsedhom/udagram-api-user:latest

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend ibrahimsedhom/udagram-frontend:latest

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-frontend ibrahimsedhom/udagram-reverseproxy:latest

after_success:
  -  docker login -u "ibrahimsedhom" --password-stdin
  - docker push ibrahimsedhom/udagram-api-feed:latest
  - docker push ibrahimsedhom/udagram-api-user:latest
  - docker push ibrahimsedhom/udagram-frontend:latest
  - docker push ibrahimsedhom/udagram-reverseproxy:latest
