language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - sudo docker --version # print the version for logging
  - sudo docker build -t udagram-api-feed ./udagram-api-feed
  - sudo docker tag udagram-api-feed  ibrahimsedhom/udagram-api-feed:v2

 - sudo docker build -t udagram-api-user ./udagram-api-user
  - sudo docker tag udagram-user ibrahimsedhom/udagram-api-user:v2

 - sudo docker build -t udagram-api-frontend ./udagram-api-frontend
  - sudo docker tag udagram-frontend ibrahimsedhom/udagram-api-frontend:v2

- sudo docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
  - sudo docker tag udagram-reverseproxy ibrahimsedhom/udagram-api-reverseproxy:v2
after_success:
  -    - sudo docker login --username "ibrahimsedhom"  --password "1234_2023"
  - docker push ibrahimsedhom/udagram-api-feed:v2
  - docker push ibrahimsedhom/udagram-api-user:v2
  - docker push ibrahimsedhom/udagram-frontend:v2
  - docker push ibrahimsedhom/udagram-reverseproxy:v2
